### ISSUE TITLE
Travis CI build failing PHP version 7.1

### ISSUE THREAD

**Issue by Jhnbrn90** [nunomaduro/phpinsights#151]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| Library version  | 1.5.0

_I guess this question is more related to Travis CI, but here it goes..._

After adding PHP Insights to a project, the Travis CI build for PHP version 7.1 expectedly fails, since this package is PHP 7.2+.

**My question:** Is it possible to run PHP Unit in a PHP 7.1 environment on Travis CI, making composer skip the installation of PHP Insights?

-----

The error on Travis CI: 

> Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - Installation request for nunomaduro/phpinsights ^1.5 -> satisfiable by nunomaduro/phpinsights[v1.5.0].
    - nunomaduro/phpinsights v1.5.0 requires php ^7.2 -> your PHP version (7.1.11) does not satisfy that requirement.

My .travis.yml config file:
```yaml
language: php

php:
  - 7.1
  - 7.2
  - 7.3

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source
  - cp .env.example .env
  - php artisan key:generate

script:
  - vendor/bin/phpunit
```
