### ISSUE TITLE
Only process changed files when using Github Actions

### ISSUE THREAD

**Issue by joostsolvari** [nunomaduro/phpinsights#354]
| Q                | A
| ---------------- | -----
| Bug report?      |no
| Feature request? | yes
| Library version  | 1.12.0

Dear community,

Does anyone have found a way to only process changed files in a PR when using Github Actions? Would love that.. my tests take > 20 min :')

Would be nice to explain on https://phpinsights.com/continuous-integration.html#disable-security-check

Thanks in advance!

**Comment by olivernybroe** [comment]
This is currently not possible, but seems like a nice feature to have 👍

**Comment by Jibbarth** [comment]
Yes it's a real need to launch analyse on a list of file, instead a directory or one file.

**Comment by olivernybroe** [comment]
I opened a issue #355 for multi files/ folders. I think adding support for that first, will make adding support for this much easier.

**Comment by 50bhan** [comment]
@olivernybroe Do you think can we go for this now?

**Comment by Jibbarth** [comment]
@50bhan is there anything to change in code ? In my mind, it's just adding some documentation, right ? 

Do you see something else ?

**Comment by 50bhan** [comment]
@Jibbarth No, I don't think so. We just need to update the docs with proper command. And it crossed my mind, what if we use it as well?

**Comment by Jibbarth** [comment]
Here is how we handle it in our github-action workflow: 

```yaml
            - name: PHPInsight on modified files
              if: github.event_name == 'pull_request'
              run: |
                  URL="https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/${{ github.event.pull_request.number }}/files"
                  FILES=$(curl -s -X GET -G $URL | jq -r '.[] |  select( .status == "added" or .status == "modified") | .filename')
                  php bin/phpinsights analyse $FILES --ansi -v --no-interaction --format=github-action --min-quality=0 --min-complexity=0 --min-architecture=0 --min-style=0

```

Refs https://github.com/nunomaduro/phpinsights/blob/master/.github/workflows/format.yaml#L51-L56
