### ISSUE TITLE
Using PHP Insights with BitBucket?

### ISSUE THREAD

**Issue by ajmeireles** [nunomaduro/phpinsights#551]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| Library version  | latest

---

Hi, everyone!

It's a just question! Can I use the phpinsights with BitBucket pipeline integration?

**Comment by 50bhan** [comment]
@ajmeireles Of course, you can. You can find more detailed information here: https://phpinsights.com/continuous-integration.html

**Comment by Marshud** [comment]
Thanks @50bhan however, the above link only shows Github Action and GitLab Code Quality, Bitbucket isn't mentioned anywhere. However, I will try running it as an extra step in the pipeline and see how it goes.

**Comment by 50bhan** [comment]
Yes, you are right. Maybe you could PR the workaround afterward 🙂 I believe you can run it by adding something like this:

```
    - step: &code-analysis
        name: PHP Insights
        caches:
          - laravel-vendor
        script:
          - composer install --prefer-dist --no-progress --no-suggest
          - vendor/bin/phpinsights -n --ansi
```
