### ISSUE TITLE
ErrorException - Undefined array key "database"

### ISSUE THREAD

**Issue by catabozan** [nunomaduro/phpinsights#592]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| Library version  | ^2.3

Everything works fine on local environment, but a weird error appears on GitHub actions.

This is the error I get:
```bash
 ErrorException 

  Undefined array key "database"

  at vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php:76
     72▕     {
     73▕         $pdo = $this->createPdoResolver($config);
     74▕ 
     75▕         return $this->createConnection(
  ➜  76▕             $config['driver'], $pdo, $config['database'], $config['prefix'], $config
     77▕         );
     78▕     }
     79▕ 
     80▕     /**

      +14 vendor frames 
  15  src/App/Providers/AppServiceProvider.php:28
      Illuminate\Support\Facades\Facade::__callStatic()

      +7 vendor frames 
  23  [internal]:0
      Illuminate\Foundation\Application::Illuminate\Foundation\{closure}()
Error: Process completed with exit code 1.
```
And this is the GitHub action:

```yaml
name: Code analysis (phpinsights and larastan)
on: [push, pull_request]
jobs:
  phpinsights:
    runs-on: ubuntu-latest

    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"

      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Analyze code with PHP insights
        run: php artisan insights -n --ansi --format=github-action
```

Have you ever encountered this error before? What could be the possible cause of this?
