### ISSUE TITLE
Github actions skips config file

### ISSUE THREAD

**Issue by Hoopex** [nunomaduro/phpinsights#649]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| Library version  | latest

Hello
I use this https://phpinsights.com/continuous-integration.html#github-action to create a CI workflow

```
jobs:
    phpinsights:
        runs-on: ubuntu-latest
        name: PHP Insights checks
        steps:
            - uses: actions/checkout@v2
            - uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.1
            - run: composer install --prefer-dist --no-progress --no-suggest
            - run: vendor/bin/phpinsights -n --ansi --format=github-action
```

The only thing i changed is php version to `8.1` but running the script ignores my config file, even when i used  `--config-path=config/insights.php` but still not working.
